### ISSUE TITLE
Regular crash

### ISSUE THREAD

**Issue by PianSom** [eschava/broadlink-mqtt#9] opened 2017-04-14 13:02 UTC
Hi I am regularly getting the following crash when replaying a 433MHz file:

[2017-04-14 11:25:20,636] ERROR Error
Traceback (most recent call last):
  File "/home/pi/mqtt-py/mqtt.py", line 83, in on_message
    replay(device, file)
  File "/home/pi/mqtt-py/mqtt.py", line 141, in replay
    device.send_data(ir_packet.decode('hex'))
  File "/usr/local/lib/python2.7/dist-packages/broadlink/__init__.py", line 450, in send_data
    self.send_packet(0x6a, packet)
  File "/usr/local/lib/python2.7/dist-packages/broadlink/__init__.py", line 250, in send_packet
    response = self.cs.recvfrom(1024)
timeout: timed out

Any suggestions?

Thanks

**Comment by eschava** [comment] 2017-04-14 13:04
Is it 100% reproducible?

**Comment by PianSom** [comment] 2017-04-14 13:13
Sadly not 100%. Just random. 

But regular - here's a cat mqtt.log | grep ERROR showing timings for the last few days:

[2017-04-12 16:23:08,505] ERROR Error
[2017-04-12 16:23:09,519] ERROR Error
[2017-04-12 16:23:11,633] ERROR Error
[2017-04-12 16:23:13,024] ERROR Error
[2017-04-12 16:23:19,332] ERROR Error
[2017-04-12 20:40:14,112] ERROR Error
[2017-04-12 20:41:27,007] ERROR Error
[2017-04-12 20:46:27,742] ERROR Error
[2017-04-12 20:50:48,927] ERROR Error
[2017-04-12 20:50:48,975] ERROR Error
[2017-04-12 20:50:50,963] ERROR Error
[2017-04-12 20:51:07,947] ERROR Error
[2017-04-12 20:51:08,856] ERROR Error
[2017-04-12 20:51:09,534] ERROR Error
[2017-04-12 20:51:10,279] ERROR Error
[2017-04-12 20:51:10,821] ERROR Error
[2017-04-12 20:51:13,381] ERROR Error
[2017-04-12 20:53:24,697] ERROR Error
[2017-04-12 20:53:26,746] ERROR Error
[2017-04-12 20:53:27,891] ERROR Error
[2017-04-12 20:53:29,684] ERROR Error
[2017-04-12 20:53:33,093] ERROR Error
[2017-04-12 21:01:50,934] ERROR Error
[2017-04-12 21:09:00,572] ERROR Error
[2017-04-12 21:09:02,914] ERROR Error
[2017-04-12 21:09:21,632] ERROR Error
[2017-04-12 21:09:35,189] ERROR Error
[2017-04-12 21:09:45,620] ERROR Error
[2017-04-12 21:10:41,183] ERROR Error
[2017-04-12 21:11:01,364] ERROR Error
[2017-04-13 09:52:55,315] ERROR Error
[2017-04-13 09:52:58,327] ERROR Error
[2017-04-13 09:52:59,923] ERROR Error
[2017-04-13 09:53:00,990] ERROR Error
[2017-04-13 09:53:01,711] ERROR Error
[2017-04-13 09:53:02,625] ERROR Error
[2017-04-13 09:53:52,885] ERROR Error
[2017-04-13 09:53:58,703] ERROR Error
[2017-04-13 09:54:05,462] ERROR Error
[2017-04-14 06:08:10,048] ERROR Error
[2017-04-14 11:24:52,934] ERROR Error
[2017-04-14 11:25:20,636] ERROR Error
[2017-04-14 13:05:34,529] ERROR Error
[2017-04-14 13:06:09,572] ERROR Error
[2017-04-14 13:06:10,582] ERROR Error

**Comment by eschava** [comment] 2017-04-24 08:43
It could be related to network issues because it fails waiting for UDP confirmation message from the device
If not - then you should report this issue to the https://github.com/mjg59/python-broadlink/issues tracker
BTW it looks similar to https://github.com/mjg59/python-broadlink/issues/45 issue and it should be fixed at next release

**Comment by ip-ua** [comment] 2017-05-10 07:05
Can you update your code?  https://github.com/mjg59/python-broadlink already updated.

**Comment by eschava** [comment] 2017-05-11 11:54
@ip-ua are you asking me or @PianSom ?

**Comment by ip-ua** [comment] 2017-05-11 12:04
You

**Comment by eschava** [comment] 2017-05-11 12:06
@ip-ua python-broadlink is used by my project as an external library and doesn't include it. API was not changed after last fixes. What exactly I have to update?

**Comment by ip-ua** [comment] 2017-05-11 17:19
So, fi I understand correctly, I just have to reinstall your project and it
will be automatically updated?

**Comment by eschava** [comment] 2017-05-12 11:51
@ip-ua No, it depends on the way how python-broadlink is installed in your system
E.g. if it was installed using pip you have to execute command
`pip install --upgrade python-broadlink`
to upgrade it to the latest version

**Closed** 2017-06-06 14:07 UTC
